name: DNScontrol check and preview

on: pull_request

jobs:
  dns-check-preview:
    name: DNScontrol check and preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: DNSControl check
        uses: koenrh/dnscontrol-action@v2.9
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: check

      - name: DNSControl preview
        uses: koenrh/dnscontrol-action@v2.9
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: preview
